### ISSUE TITLE
Error when loading subscription for ARM to ARM migration

### ISSUE THREAD

**Issue by elobpries** [Azure/migAz#106]
Receiving the following error with both 2.3.0.0 and 2.3.0.1 when loading a VS subscription:

Platform Update Domain Count must be between 5 and 20.
   at MigAz.Azure.MigrationTarget.AvailabilitySet.set_PlatformUpdateDomainCount(Int32 value)
   at MigAz.Azure.MigrationTarget.AvailabilitySet..ctor(AzureContext azureContext, AvailabilitySet availabilitySet)
   at MigAz.Azure.AzureRetriever.<LoadARMAvailabilitySets>d__146.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.AzureRetriever.<BindArmResources>d__153.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Migrators.AsmToArm.<BindArmResources>d__63.MoveNext()

**Comment by rsanderson2350** [comment]
Resolved as of v2.3.1.0
