### ISSUE TITLE
Storage Account target name cannot exceed 22 character(s)

### ISSUE THREAD

**Issue by myossiv** [Azure/migAz#116]
Storage Account target name cannot exceed 22 character(s) due to Suffix character requirements.
at MigAz.Azure.MigrationTarget.StorageAccount.SetTargetName(String targetName, TargetSettings targetSettings) in C:\Users\Yossi\Downloads\migAz-master (1)\migAz-master\MigAz.Azure\MigrationTarget\StorageAccount.cs:line 101
at MigAz.Azure.MigrationTarget.StorageAccount..ctor(IStorageAccount source, TargetSettings targetSettings) in C:\Users\Yossi\Downloads\migAz-master (1)\migAz-master\MigAz.Azure\MigrationTarget\StorageAccount.cs:line 33
at MigAz.Azure.AzureSubscription.d__230.MoveNext() in C:\Users\Yossi\Downloads\migAz-master (1)\migAz-master\MigAz.Azure\AzureSubscription.cs:line 2230
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
at MigAz.Azure.AzureSubscription.d__167.MoveNext() in C:\Users\Yossi\Downloads\migAz-master (1)\migAz-master\MigAz.Azure\AzureSubscription.cs:line 622
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
at MigAz.Azure.UserControls.MigrationAzureSourceContext.d__80.MoveNext() in C:\Users\Yossi\Downloads\migAz-master (1)\migAz-master\MigAz.Azure\UserControls\MigrationAzureSourceContext.cs:line 413

**Comment by myossiv** [comment]
Storage Account target name cannot exceed 22 character(s) due to Suffix character requirements.
   at MigAz.Azure.MigrationTarget.StorageAccount.SetTargetName(String targetName, TargetSettings targetSettings) in C:\Users\Yossi\Downloads\migAz-master (1)\migAz-master\MigAz.Azure\MigrationTarget\StorageAccount.cs:line 101
   at MigAz.Azure.MigrationTarget.StorageAccount..ctor(IStorageAccount source, TargetSettings targetSettings) in C:\Users\Yossi\Downloads\migAz-master (1)\migAz-master\MigAz.Azure\MigrationTarget\StorageAccount.cs:line 33
   at MigAz.Azure.AzureSubscription.<LoadARMStorageAccounts>d__230.MoveNext() in C:\Users\Yossi\Downloads\migAz-master (1)\migAz-master\MigAz.Azure\AzureSubscription.cs:line 2230
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MigAz.Azure.AzureSubscription.<BindArmResources>d__167.MoveNext() in C:\Users\Yossi\Downloads\migAz-master (1)\migAz-master\MigAz.Azure\AzureSubscription.cs:line 622
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MigAz.Azure.UserControls.MigrationAzureSourceContext.<BindArmResources>d__80.MoveNext() in C:\Users\Yossi\Downloads\migAz-master (1)\migAz-master\MigAz.Azure\UserControls\MigrationAzureSourceContext.cs:line 413

**Comment by rsanderson2350** [comment]
Should be resolved, please download v2.3.3.1

**Comment by myossiv** [comment]
I am using the last version
yet I have this issue 
i need to open the software from the start each time in order to not get this error
it is not good

**Comment by rsanderson2350** [comment]
You are still running v2.3.3.0.  v2.3.3.1 no longer contains code that throws the exception.  Please download v2.3.3.1 from the [Release folder](https://github.com/Azure/migAz/tree/master/Release).
