### ISSUE TITLE
Unhandled Exception in MigAz (GetSASURLAsync Disk)

### ISSUE THREAD

**Issue by richardajyoung** [Azure/migAz#126]
Using latest version.
Setting up to copy VM with Managed Disks from one subscription to another (ARM->ARM).

The VM has two managed disks attached. One OS and one Data.

My machine is running Windows 10 Pro (1710) x64.

Error occurs when clicking on "Export Objects" button

The log shows the error occurs after this (heavily edited) entry. The first line doesn't seem to create an error - it occurs after the second line:
GetSASUrlAsync  Disk 'MyDiskName' PostAsync /subscriptions/MySubscriptionID/resourceGroups/SourceResourceGroupName/providers/Microsoft.Compute/disks/MyDIskName/BeginGetAccess?api-version=2017-03-30
GetSASUrlAsync  Disk 'MyDiskName' GetAsync /subscriptions/MySubscriptionID/providers/Microsoft.Compute/locations/Australia East/DiskOperations/SomeLongGUID?api-version=2017-03-30

Trace:
Object reference not set to an instance of an object.
   at MigAz.Azure.Arm.ManagedDisk.<GetSASUrlAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.Generator.TemplateGenerator.<BuildCopyBlob>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.Generator.TemplateGenerator.<GenerateStreams>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Forms.MigAzForm.<RefreshOutput>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Forms.MigAzForm.<btnExport_Click_1Async>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by rsanderson2350** [comment]
In the testing that I have completed so far, I have been able to reproduce an "Object reference not set to an instance of an object" error under only one condition.  Am I correct that the Source VM with Managed Disks you are trying to copy from is in a Running / Provisioned state?  This is the only condition under which I have been able to get the same error message so far.

I will add further code to handle this.  The MigAz tool does require the Source VM (which has Managed Disks) to be in a Stopped / Deallocated state in order to be able to obtain the SAS URL of the Managed Disk(s).  The MigAz tool does not yet have code to snapshot a running Managed Disk VM, thus, the VM must be stopped.

Can you stop the VM and try your copy process again?

**Comment by richardajyoung** [comment]
Hi,

You are correct that the VM is up and running. I was trying to download the ARM templates to work on them before the change window to move them to their new subscription!
At the moment the servers are not members of Availability Sets, and I wanted to fix that up before the Change Window which is when they would have been shut down!

I'll test the theory on one of the test servers and get back to you.

Thank you for looking at this issue so quickly. It's appreciated!

**Comment by rsanderson2350** [comment]
Yes, any time you try to generate the template of an ARM Managed Disk VM, it tries to get the SAS URLs to the VHD files (which it can't do when it is running).  When are you planning on doing the actual migration in which you want to add to a new Availability Set?

**Comment by richardajyoung** [comment]
Hi. Probably next week depending on Change Board approval. I tend to rename components too if they've had the random names that Azure assigns, plus remove things like PIP's that were added by default.

Side issue: I've also noticed that I can't always change the destination VNet/Subnet for a NIC that I want to migrate. I have to change the Target Subscription a couple of times first!

**Comment by richardajyoung** [comment]
Confirmed that shutting the VM down enables the template creation.

Thank you for your help!
