### ISSUE TITLE
multiple_matching_tokens_detected

### ISSUE THREAD

**Issue by myossiv** [Azure/migAz#130]
multiple_matching_tokens_detected: The cache contains multiple tokens satisfying the requirements. Call AcquireToken again providing more arguments (e.g. UserId)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache.LoadSingleItemFromCache(CacheQueryData cacheQueryData, CallState callState)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache.LoadFromCache(CacheQueryData cacheQueryData, CallState callState)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenCommonAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Comment by rsanderson2350** [comment]
Use of token cache was just recently added, and I have not yet run into this.  Are you able to reproduce this error consistently?  If so, are you able to provide sample steps to reproduce the error?  Am I correct you are trying to use two different accounts (between source and target)?

**Comment by myossiv** [comment]
Just tried to login to the tannent
Yes u r right...

On Feb 21, 2018 12:38 AM, "rsanderson2350" <notifications@github.com> wrote:

Use of token cache was just recently added, and I have not yet run into
this. Are you able to reproduce this error consistently? If so, are you
able to provide sample steps to reproduce the error? Am I correct you are
trying to use two different accounts (between source and target)?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Azure/migAz/issues/130#issuecomment-367145738>, or mute
the thread

**Comment by rsanderson2350** [comment]
Use of UserId has been implemented as of v2.4.0.0 release and testing with different source / target accounts seems to show this is working well.  This issue should be resolved.
