### ISSUE TITLE
MigAZ Unhandled Exception with Managed Disks

### ISSUE THREAD

**Issue by helbadini** [Azure/migAz#135]
I'm getting the following error when I try to clone VMs with managed disks. Please help. 

----
Object reference not set to an instance of an object.
   at MigAz.Azure.Arm.ManagedDisk.<GetSASUrlAsync>d__35.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\Arm\ManagedDisk.cs:line 212
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.Generator.TemplateGenerator.<BuildCopyBlob>d__65.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\Generator\TemplateGenerator.cs:line 1288
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.Generator.TemplateGenerator.<GenerateStreams>d__51.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\Generator\TemplateGenerator.cs:line 221
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Forms.MigAzForm.<RefreshOutput>d__48.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz\Forms\MigAzForm.cs:line 449
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Forms.MigAzForm.<btnExport_Click_1Async>d__42.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz\Forms\MigAzForm.cs:line 346
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by rsanderson2350** [comment]
Duplicate to #129, #126, #121. Stop the VM(s) that have Managed Disk(s) prior to exporting.
