### ISSUE TITLE
exception while enumerating ARM objects 

### ISSUE THREAD

**Issue by julianmallett** [Azure/migAz#146]
Hi steps to recreate:

Connect to EA subscription, while enumerating the ARM artefacts on first login, the following exception occurs. When I connect to the ASM artefacts are enumerated as expected. Then switch back to the ARM dropdown selector, I see the artefacts are visible in the tree view.  It appears to be failing when enumerating a resource group that only contains 2 classic vms, the associated cloud service and a classic storage account.

I will try and confirm on an earlier version.

thanks

Object reference not set to an instance of an object.
   at MigAz.Azure.Arm.VirtualMachine..ctor(AzureSubscription azureSubscription, JToken resourceToken) in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\Arm\VirtualMachine.cs:line 31
   at MigAz.Azure.AzureSubscription.<GetAzureArmVirtualMachines>d__168.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:line 1584
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureSubscription.<LoadARMVirtualMachines>d__192.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:line 2252
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.AzureSubscription.<BindArmResources>d__127.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:line 720
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.UserControls.TreeViewSourceResourceManager.<BindArmResources>d__43.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\UserControls\TreeViewSourceResourceManager.cs:line 129

**Comment by julianmallett** [comment]
ok just confirmed doesn't happen on 2.4.0.1

**Comment by rsanderson2350** [comment]
In the last release, the code was updated to locate the ARM Managed Disk and associate / relate said c# object to the c# Virtual Machine object.  Line 30 of the Virtual Machine class constructor reads the Azure Resource ID of the OS Managed Disk and then Line 31 where you are erroring on Object Reference not set to an instance of an object indicates it has a null value (was not able to get the ID of the OS Managed Disk).  Can you review the Virtual Machine JSON to see if why it would be missing the Managed DIsk ID:

ResourceToken["properties"]["storageProfile"]["osDisk"]["managedDisk"]["id"]

**Comment by rsanderson2350** [comment]
Please advise if this is still occurring, utilizing the latest release (v2.4.2.1).  This should be resolved.
