### ISSUE TITLE
getting exception while enumerating ressources

### ISSUE THREAD

**Issue by Antse** [Azure/migAz#148]
<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>ResourceNotFound</Code><Message>Role neoeudevnecd14 was not found in the currently deployed service.</Message></Error>

The remote server returned an error: (404) Not Found.

   at MigAz.Azure.AzureRetriever.<GetAzureRestResponse>d__14.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureRetriever.cs:line 180
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.AzureSubscription.<GetAzureAsmResources>d__184.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:line 2057
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureSubscription.<GetAzureAsmVirtualMachine>d__141.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:line 970
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.Asm.CloudService.<InitializeChildrenAsync>d__34.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\Asm\CloudService.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureSubscription.<GetAzureAsmCloudServices>d__144.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:line 1112
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.AzureSubscription.<BindAsmResources>d__126.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:line 503
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.UserControls.MigrationAzureSourceContext.<BindAsmResources>d__87.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\UserControls\MigrationAzureSourceContext.cs:line 277

**Comment by rsanderson2350** [comment]
Seems to be while querying the ASM RoleSizes.  Which Azure Environment are you connected to for the subscription?  Does the Subscription have ASM Resources?

**Comment by Antse** [comment]
Subsription has both ASM and ARM ressources, i choose mig from ASM to ARM.

**Comment by Antse** [comment]
forget it, i understand my mistake ^^ !
