### ISSUE TITLE
Unhandled exception - No registered resource provider found for location 'francesouth' and API version '2017-03-30' for type 'locations/vmSizes' in the version 2.3.2.1

### ISSUE THREAD

**Issue by ShamSV** [Azure/migAz#157]
I see the following issue in the new version 2.3.2.1.

{"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'francesouth' and API version '2017-03-30' for type 'locations/vmSizes'. The supported api-versions are '2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview, 2016-08-30, 2017-03-30, 2017-12-01'. The supported locations are 'eastus, eastus2, westus, centralus, northcentralus, southcentralus, northeurope, westeurope, eastasia, southeastasia, japaneast, japanwest, australiaeast, australiasoutheast, brazilsouth, southindia, centralindia, westindia, canadacentral, canadaeast, westus2, westcentralus, uksouth, ukwest, koreacentral, koreasouth, francecentral'."}}

The remote server returned an error: (400) Bad Request.

   at MigAz.Azure.AzureRetriever.<GetAzureRestResponse>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureSubscription.<GetAzureARMLocationVMSizes>d__205.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.Arm.Location.<InitializeChildrenAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureSubscription.<GetAzureARMLocations>d__170.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureSubscription.<BindArmResources>d__169.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.UserControls.MigrationAzureSourceContext.<BindArmResources>d__70.MoveNext()

**Comment by rsanderson2350** [comment]
Thanks for logging this as a separate issue.  I saw this once during development, but wasn't able to capture it.  The france data centers are new.  This issue seems to occur, but then goes away (meaning doesn't work but then does work a little later without MigAz code change).  Seeing what I can do to reproduce, or at least simulate the failure, and add error handling.

**Comment by ShamSV** [comment]
Getting the following error when logging into the destination subscription:

Object reference not set to an instance of an object.
   at MigAz.Azure.Arm.VirtualMachine..ctor(AzureSubscription azureSubscription, JToken resourceToken) in C:\Users\ruanders\source\repos\migAz\MigAz.Azure\Arm\VirtualMachine.cs:line 78
   at MigAz.Azure.AzureSubscription.<GetAzureArmVirtualMachines>d__184.MoveNext() in C:\Users\ruanders\source\repos\migAz\MigAz.Azure\AzureSubscription.cs:line 1641
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureSubscription.<LoadARMVirtualMachines>d__210.MoveNext() in C:\Users\ruanders\source\repos\migAz\MigAz.Azure\AzureSubscription.cs:line 2377
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.AzureSubscription.<BindArmResources>d__143.MoveNext() in C:\Users\ruanders\source\repos\migAz\MigAz.Azure\AzureSubscription.cs:line 777
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureContext.<SetSubscriptionContext>d__73.MoveNext() in C:\Users\ruanders\source\repos\migAz\MigAz.Azure\AzureContext.cs:line 192
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.UserControls.AzureArmLoginControl.<cmbSubscriptions_SelectedIndexChanged>d__6.MoveNext() in C:\Users\ruanders\source\repos\migAz\MigAz.Azure\UserControls\AzureArmLoginControl.cs:line 219
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by rsanderson2350** [comment]
Like 78 of Arm Virtual Machine is indicating that the VM has at least one managed disk and that it was not able to "find" that disk.

- Do you know which of your VMs this is specifically occurring on?  
- Are the Data Disk(s) Managed DIsks, and are they in the same Resource Group as the VM?
- Can you provide the JSON from the REST API calls for this specific VM (feel free to filter out any company names, subscription ids, etc.).  

I am specifically looking at what the JSON has in the ["properties"]["storageProfile"]["dataDisks"] section of the VM.

**Comment by ShamSV** [comment]
Its failing at a ResourceGroup that doesn't have any VM. the RG is specific for VSTS preview.
There are other issues like: the selected subscription is not shown under target subscription.
At times its randomly failing at a VM without any managed disks nor any data disk.

Somehow the querying of the target resources is not getting complete or having issues...

**Comment by ShamSV** [comment]
This subscription has quite a lot of VMs and different resources. Its not failing on one particular VM every time. The same environment worked fine when we migrated few VMs using the 2.2.* and 2.3.* versions.
