### ISSUE TITLE
Issue when get information about NetworkWatcher

### ISSUE THREAD

**Issue by edmarcardoso** [Azure/migAz#158]
Hello, 

I am running the v2.4.2.1 .

Object reference not set to an instance of an object.
   at MigAz.Azure.Arm.VirtualMachine..ctor(AzureSubscription azureSubscription, JToken resourceToken) in C:\Users\ruanders\source\repos\migAz\MigAz.Azure\Arm\VirtualMachine.cs:line 46
   at MigAz.Azure.AzureSubscription.<GetAzureArmVirtualMachines>d__184.MoveNext() in C:\Users\ruanders\source\repos\migAz\MigAz.Azure\AzureSubscription.cs:line 1641
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureSubscription.<LoadARMVirtualMachines>d__210.MoveNext() in C:\Users\ruanders\source\repos\migAz\MigAz.Azure\AzureSubscription.cs:line 2377
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.AzureSubscription.<BindArmResources>d__143.MoveNext() in C:\Users\ruanders\source\repos\migAz\MigAz.Azure\AzureSubscription.cs:line 777
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureContext.<SetSubscriptionContext>d__73.MoveNext() in C:\Users\ruanders\source\repos\migAz\MigAz.Azure\AzureContext.cs:line 192
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.UserControls.AzureArmLoginControl.<cmbSubscriptions_SelectedIndexChanged>d__6.MoveNext() in C:\Users\ruanders\source\repos\migAz\MigAz.Azure\UserControls\AzureArmLoginControl.cs:line 219
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by rsanderson2350** [comment]
Hi,

What indication do you have that this in in related to NetworkWatcher?  The code is erroring on the creation of a Virtual Machine; specifically, it is unable to locate the OS Managed Disk.  Do you have any output in your log file that says?:

Arm.VirutalMachine Ctor - Seeking Managed Disk By Name _____________________

Does it list a Name?  Are you able to locate that Managed Disk via the Azure Portal?

**Comment by ShamSV** [comment]
Is there are a way we can enable a log file for MigAz while it enumerate the target (destination) resources? Its failing at multiple points under different resources.

**Comment by rsanderson2350** [comment]
@ShamSV separate issue of enumerating target (destination) resources moved to issue #160
