### ISSUE TITLE
An unhandled exception has occurred in MigAz

### ISSUE THREAD

**Issue by jclark-lda** [Azure/migAz#172]
Unable to obtain SAS Token for Disk 'DlinkAzureTest_OsDisk_1_78e36dfdad1d472a8d28c7fe1a99dc10'.  Disk is attached to Virtual Machine 'DlinkAzureTest' which may be running.  MigAz can currently only obtain the SAS URL for the Managed Disk when the owning VM is stopped.  Please ensure VM is stopped.
   at MigAz.Azure.Arm.ManagedDisk.<GetSASUrlAsync>d__35.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\Arm\ManagedDisk.cs:line 236
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.Generator.TemplateGenerator.<BuildCopyBlob>d__59.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\Generator\TemplateGenerator.cs:line 1293
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.Generator.TemplateGenerator.<GenerateStreams>d__45.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\Generator\TemplateGenerator.cs:line 236
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Forms.MigAzForm.<RefreshOutput>d__51.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz\Forms\MigAzForm.cs:line 388
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Forms.MigAzForm.<btnExport_Click_1Async>d__45.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz\Forms\MigAzForm.cs:line 295
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by rsanderson2350** [comment]
Per the error message, you will need to stop the existing VM prior to exporting it.

**Comment by jclark-lda** [comment]
I discovered that if I connect to my resource before I shutdown the VM, the software detects the VM as still running and generates the error.
Quitting the software, stopping the VM and reconnecting resolved the issue.
Thank you for your assistance and for sharing this tool.

Regards,

Jay
