### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by chillryan** [Azure/migAz#173]
I was attempting to select Target Storage for an existing storage in our subscription for VM classic migration.

Object reference not set to an instance of an object.
   at MigAz.Azure.UserControls.DiskProperties.cmbTargetStorage_SelectedIndexChanged(Object sender, EventArgs e) in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\UserControls\DiskProperties.cs:line 346
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by rsanderson2350** [comment]
Please try v2.4.2.4 which should resolve the error on DiskProperites.cs Line 346.
