### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by cupanoodle** [Azure/migAz#175]
I was attempting to migrate an arm vm from one sub to another. When migaz is getting the list of resources from the source sub, I get an "Object reference not set to an instance of an object." exception.

This has been occurring on one of our subscriptions on Migaz version 2.4.2.2 through 2.4.2.4

```
Object reference not set to an instance of an object.
   at MigAz.Azure.Arm.VirtualMachine.<InitializeChildrenAsync>d__33.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\Arm\VirtualMachine.cs:line 203
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureSubscription.<GetAzureArmVirtualMachines>d__187.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:line 1664
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureSubscription.<LoadARMVirtualMachines>d__213.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:line 2399
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.AzureSubscription.<BindArmResources>d__146.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:line 800
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.UserControls.MigrationAzureSourceContext.<_AzureContext_AfterAzureSubscriptionChange>d__88.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\UserControls\MigrationAzureSourceContext.cs:line 248
```

**Comment by rsanderson2350** [comment]
Should be resolved with version 2.4.2.5.
