### ISSUE TITLE
Unhandled Exception during export

### ISSUE THREAD

**Issue by chillryan** [Azure/migAz#177]
I received this error when attempting to export an ARM->ARM migration

Object reference not set to an instance of an object.
   at MigAz.Azure.Generator.TemplateGenerator.<AddGatewaysToVirtualNetwork>d__52.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\Generator\TemplateGenerator.cs:line 605
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.Generator.TemplateGenerator.<BuildVirtualNetworkObject>d__51.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\Generator\TemplateGenerator.cs:line 598
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.Generator.TemplateGenerator.<GenerateStreams>d__45.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\Generator\TemplateGenerator.cs:line 201
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Forms.MigAzForm.<RefreshOutput>d__51.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz\Forms\MigAzForm.cs:line 388
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Forms.MigAzForm.<btnExport_Click_1Async>d__45.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz\Forms\MigAzForm.cs:line 295
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by rsanderson2350** [comment]
Should be resolved with version 2.4.2.5.
