### ISSUE TITLE
Unable to obtain SAS Token for Disk

### ISSUE THREAD

**Issue by krhynerson** [Azure/migAz#179]
I've used MigAz multiple times, but I've run across an error I cannot get around.

The error thinks the VM is running.  I confirmed it is stopped/deallocated.  I did find a SAS export lock that Azure (via MigAz) is creating on the disk as shown in the screenshot at http://www.skyliners.com/images/saserrorr.png

I cancelled the export, waited (as noted in Issue #172, and tried again.  The export fails, and the lock appears again.

Could this have anything to do with the fact the disk is a _managed disk_, but not the in the “pure” sense of the term?  The managed disk is based off a VHD file in a storage account, which is also shown in the screenshot.

**Error**
Unable to obtain SAS Token for Disk 'ECS-AZ-BACKUP_ECS-AZ-BACKUP'.  Disk is attached to Virtual Machine 'ECS-AZ-BACKUP' which may be running.  MigAz can currently only obtain the SAS URL for the Managed Disk when the owning VM is stopped.  Please ensure VM is stopped.
   at MigAz.Azure.Arm.ManagedDisk.<GetSASUrlAsync>d__35.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\Arm\ManagedDisk.cs:line 236
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.Generator.TemplateGenerator.<BuildCopyBlob>d__59.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\Generator\TemplateGenerator.cs:line 1293
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.Generator.TemplateGenerator.<GenerateStreams>d__45.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\Generator\TemplateGenerator.cs:line 236
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Forms.MigAzForm.<RefreshOutput>d__51.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz\Forms\MigAzForm.cs:line 388
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Forms.MigAzForm.<btnExport_Click_1Async>d__45.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz\Forms\MigAzForm.cs:line 295
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by Brucius** [comment]
Ok yeah, I seem to be having the same issue. Been using migaz for a while now and this issue just popped up recently. I have pasted the error log below too. Replaced the actual names of the machine and disks.


```
Unable to obtain SAS Token for Disk 'DISK'.  Disk is attached to Virtual Machine 'VM' which may be running.  MigAz can currently only obtain the SAS URL for the Managed Disk when the owning VM is stopped.  Please ensure VM is stopped.
   at MigAz.Azure.Arm.ManagedDisk.<GetSASUrlAsync>d__35.MoveNext() in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\Arm\ManagedDisk.cs:line 236
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.Generator.TemplateGenerator.<BuildCopyBlob>d__59.MoveNext() in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\Generator\TemplateGenerator.cs:line 1300
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.Generator.TemplateGenerator.<GenerateStreams>d__45.MoveNext() in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\Generator\TemplateGenerator.cs:line 236
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Forms.MigAzForm.<RefreshOutput>d__51.MoveNext() in C:\Users\Russell\Source\Repos\migAz\MigAz\Forms\MigAzForm.cs:line 388
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Forms.MigAzForm.<btnExport_Click_1Async>d__45.MoveNext() in C:\Users\Russell\Source\Repos\migAz\MigAz\Forms\MigAzForm.cs:line 295
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
```
