### ISSUE TITLE
Error in MigAz  2.2.14.0

### ISSUE THREAD

**Issue by GustiM** [Azure/migAz#180]
{"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'francesouth' and API version '2016-04-30-preview' for type 'locations/vmSizes'. The supported api-versions are '2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview, 2016-08-30, 2017-03-30, 2017-12-01, 2018-04-01'. The supported locations are 'eastus, eastus2, westus, centralus, northcentralus, southcentralus, northeurope, westeurope, eastasia, southeastasia, japaneast, japanwest, australiaeast, australiasoutheast, brazilsouth, southindia, centralindia, westindia, canadacentral, canadaeast, westus2, westcentralus, uksouth, ukwest, koreacentral, koreasouth, francecentral'."}}

The remote server returned an error: (400) Bad Request.

   at MigAz.Azure.AzureRetriever.<GetAzureRestResponse>d__84.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureRetriever.<GetAzureARMLocationVMSizes>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.Arm.Location.<InitializeChildrenAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureRetriever.<GetAzureARMLocations>d__67.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.AzureRetriever.<BindAsmResources>d__85.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Migrators.AsmToArm.<BindAsmResources>d__62.MoveNext()

**Comment by rsanderson2350** [comment]
Previously discussed in issue #157.  The interesting part about this error is that is seems to be very rare in occurrence (i.e. if and when it occurs, it does so for a little bit, but then goes away).  Additionally, the code queries the providers to identify what API version + what locations are available.  The provider information reported back that francesouth was an available region for querying VmSizes; however, when MigAz attempts to then query the VmSizes in francesouth, it then reports back that it not available in francesouth.

While a very rare error (I've seen it once, but has not occurred again for me), I'll look to add some soft try/catch to enable the application to continue running (thus, with no VmSizes available for the errored region, as they were not queried).  This will at least allow the application to "continue" without a hard stop while querying the region information for VmSizes.

**Comment by reisi1** [comment]
I can reproduce the issue.

`24.07.2019 11:07:48   InitializeARMVMSizes  End - Location : southafricanorth
24.07.2019 11:07:48   UnhandledExceptionDialog  {"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'australiacentral2' and API version '2019-07-01' for type 'locations/vmSizes'. The supported api-versions are '2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview, 2016-08-30, 2017-03-30, 2017-12-01, 2018-04-01, 2018-06-01, 2018-10-01, 2019-03-01, 2019-07-01'. The supported locations are 'eastus, eastus2, westus, centralus, northcentralus, southcentralus, northeurope, westeurope, eastasia, southeastasia, japaneast, japanwest, australiaeast, australiasoutheast, australiacentral, brazilsouth, southindia, centralindia, westindia, canadacentral, canadaeast, westus2, westcentralus, uksouth, ukwest, koreacentral, koreasouth, francecentral, southafricanorth, uaenorth'."}}

The remote server returned an error: (400) Bad Request.

   at MigAz.Azure.AzureRetriever.<GetAzureRestResponse>d__19.MoveNext() in C:\Users\ruanders.NORTHAMERICA\Source\Repos\migAz\MigAz.Azure\AzureRetriever.cs:line 208
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.Arm.Location.<InitializeARMVMSizes>d__20.MoveNext() in C:\Users\ruanders.NORTHAMERICA\Source\Repos\migAz\MigAz.Azure\Arm\Location.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.Arm.Location.<InitializeChildrenAsync>d__5.MoveNext() in C:\Users\ruanders.NORTHAMERICA\Source\Repos\migAz\MigAz.Azure\Arm\Location.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureSubscription.<InitializeChildrenAsync>d__53.MoveNext() in C:\Users\ruanders.NORTHAMERICA\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:line 151
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.UserControls.MigrationAzureSourceContext.<_AzureContext_AfterAzureSubscriptionChange>d__88.MoveNext() in C:\Users\ruanders.NORTHAMERICA\Source\Repos\migAz\MigAz.Azure\UserControls\MigrationAzureSourceContext.cs:line 247
24.07.2019 11:07:52   BindArmResources  Azure Subscription Child Initialization not yet started or not yet completed.  Skipping BindArmResources.
`

**Comment by ruandersMSFT** [comment]
Released v2.4.4.5.
