### ISSUE TITLE
Unhandled Exception 

### ISSUE THREAD

**Issue by makelly1974** [Azure/migAz#191]
Getting the following error when MigAz is trying to scan the resources in the source sub,
ARM subscription to ARM subscription migration.
Version 2.4.2.5

Azure account being used has contrib rights 

Object reference not set to an instance of an object.
   at MigAz.Azure.Arm.VirtualMachine.<InitializeChildrenAsync>d__33.MoveNext() in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\Arm\VirtualMachine.cs:line 203
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureSubscription.<GetAzureArmVirtualMachines>d__187.MoveNext() in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:line 1664
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureSubscription.<LoadARMVirtualMachines>d__213.MoveNext() in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:line 2399
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.AzureSubscription.<BindArmResources>d__146.MoveNext() in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:line 800
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.UserControls.MigrationAzureSourceContext.<_AzureContext_AfterAzureSubscriptionChange>d__88.MoveNext() in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\UserControls\MigrationAzureSourceContext.cs:line 248

**Comment by rsanderson2350** [comment]
Reference to #175, which identified same class (MigAz.Azure\Arm\VirtualMachine.cs) line 203.  In version 2.4.2.5, this line was expanded to include a null reference check (thus, can no longer fail with "Object reference not set to an instance of an object").  Are you sure you have 2.4.2.5 downloaded?

Code Commit:  https://github.com/rsanderson2350/migAz/commit/18289fb48a095e14625cacec0db1740f581aa013

**Comment by makelly1974** [comment]
Hi, 

Yes I have the used new 2.4.2.5 release but go the same error msg at the same scan point in the subscription

**Comment by makelly1974** [comment]
Hi,

Do you have any update regarding the issue above ?

**Comment by rsanderson2350** [comment]
v2.4.3.0 now available.  Please review and advise if resolved / still open issue.
