### ISSUE TITLE
The remote server returned an error: (409) Conflict when scanning a locked Resource Group

### ISSUE THREAD

**Issue by lukemurraynz** [Azure/migAz#194]
Error below when scanning a subscripton with a locked Resource Group. It also seems to be looking for files that don't exist in that location on my computer: C:\Users\Russell\*

{"error":{"code":"ScopeLocked","message":"The scope '/subscriptions/<SUBSCRIPTIONIDHERE>/resourceGroups/databricks-rg-DataBricks-7wxpeipi7bhlo/providers/Microsoft.Storage/storageAccounts/dbstorageeoqzdyxbdvhma' cannot perform write operation because following scope(s) are locked: '/subscriptions/<SUBSCRIPTIONIDHERE>/resourceGroups/databricks-rg-DataBricks-7wxpeipi7bhlo'. Please remove the lock and try again."}}

The remote server returned an error: (409) Conflict.

   at MigAz.Azure.AzureRetriever.<GetAzureRestResponse>d__19.MoveNext() in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\AzureRetriever.cs:line 196
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.AzureSubscription.<GetAzureARMResources>d__207.MoveNext() in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:line 2321
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureSubscription.<GetAzureARMStorageAccountKeys>d__189.MoveNext() in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:line 1711
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.AzureSubscription.<GetAzureARMStorageAccounts>d__179.MoveNext() in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:line 1511
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureSubscription.<LoadARMStorageAccounts>d__214.MoveNext() in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:line 2461
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.AzureSubscription.<BindArmResources>d__146.MoveNext() in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:line 765
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.UserControls.MigrationAzureSourceContext.<_AzureContext_AfterAzureSubscriptionChange>d__88.MoveNext() in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\UserControls\MigrationAzureSourceContext.cs:line 248

**Comment by rsanderson2350** [comment]
Added 409 Conflict check in v2.4.3.0
