### ISSUE TITLE
Error connecting to azure via migaz

### ISSUE THREAD

**Issue by nizen054** [Azure/migAz#201]
01-Aug-18 16:15:33   GetToken  Start token request : Azure AD Tenant ID 8181d1be-1471-47c0-b099-b8b5d4c43974
01-Aug-18 16:15:33   GetToken   - Resource Url: https://graph.windows.net/
01-Aug-18 16:15:33   GetToken   - Azure AD Tenant Guid: 8181d1be-1471-47c0-b099-b8b5d4c43974
01-Aug-18 16:15:33   GetToken   - Prompt Behavior: Never
01-Aug-18 16:15:33   GetToken   - Required User: <REMOVED>
01-Aug-18 16:15:33   GetToken  End token request
01-Aug-18 16:15:33   GetAzureRestResponse  24266de7-655e-4c9c-8c4e-ff5e8e28d231 Url: https://graph.windows.net/myorganization/domains?api-version=1.6
01-Aug-18 16:15:33   GetAzureRestResponse  24266de7-655e-4c9c-8c4e-ff5e8e28d231 Received REST Response
01-Aug-18 16:15:33   GetAzureRestResponse  24266de7-655e-4c9c-8c4e-ff5e8e28d231 GET https://graph.windows.net/myorganization/domains?api-version=1.6
01-Aug-18 16:15:33   GetAzureRestResponse  24266de7-655e-4c9c-8c4e-ff5e8e28d231 EXCEPTION The remote server returned an error: (403) Forbidden.
01-Aug-18 16:15:33   GetAzureRestResponse  24266de7-655e-4c9c-8c4e-ff5e8e28d231 EXCEPTION HttpWebResponse Status Code: Forbidden
01-Aug-18 16:15:33   GetAzureRestResponse  24266de7-655e-4c9c-8c4e-ff5e8e28d231https://graph.windows.net/myorganization/domains?api-version=1.6  EXCEPTION The remote server returned an error: (403) Forbidden.
01-Aug-18 16:15:33   UnhandledExceptionDialog  {"odata.error":{"code":"Authentication_Unauthorized","message":{"lang":"en","value":"User was not found."}}}

{"odata.error":{"code":"Authentication_Unauthorized","message":{"lang":"en","value":"User was not found."}}}

The remote server returned an error: (403) Forbidden.

   at MigAz.Azure.AzureRetriever.<GetAzureRestResponse>d__19.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureRetriever.cs:line 208
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureTenant.<GetAzureARMDomains>d__23.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureTenant.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureTenant.<InitializeChildren>d__22.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureTenant.cs:line 85
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureContext.<GetAzureARMTenants>d__74.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureContext.cs:line 233
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.UserControls.AzureArmLoginControl.<btnAuthenticate_Click>d__5.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\UserControls\AzureArmLoginControl.cs:line 151
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by rsanderson2350** [comment]
Recommend reviewing issue #47, #69 and #73. Historically, with regards to ASM permissions, users have needed to ensure the user account they are authenticating with has been granted co-administrator access to the ASM Subscription in the Azure Classic Portal.

https://docs.microsoft.com/en-us/azure/billing/billing-add-change-azure-subscription-administrator

See the "Azure classic portal" section.

**Comment by nizen054** [comment]
Hi
i'm not using the ASM to ARM migration.
i'm using only ARM to ARM

ניצן:)

**Comment by rsanderson2350** [comment]
Same conditions should still apply for resolution.  The account you are using does not have access to query the Graph API for available Tenant List.  Try increasing permissions as indicated by previous resolution.
