### ISSUE TITLE
Error when logging into ARM Type

### ISSUE THREAD

**Issue by recintoit** [Azure/migAz#209]
Hello,
I used MigAz prior with the ASM/Classic type but I get this error when trying to login with the application .exe.   It's looking for a path that is not my local user.

However when I switch back, it shows my resources.  Is this a known issue?

Object reference not set to an instance of an object.
   at MigAz.Azure.Arm.VirtualMachine.<InitializeChildrenAsync>d__33.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\Arm\VirtualMachine.cs:line 203
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureSubscription.<GetAzureArmVirtualMachines>d__187.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:line 1664
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureSubscription.<LoadARMVirtualMachines>d__213.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:line 2399
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.AzureSubscription.<BindArmResources>d__146.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:line 800
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.UserControls.MigrationAzureSourceContext.<_AzureContext_AfterAzureSubscriptionChange>d__88.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\UserControls\MigrationAzureSourceContext.cs:line 248

**Comment by ruandersMSFT** [comment]
The file path is specific to my compilation direction, something I'll look to change in the future (it does not reference you file structure).  This should be resolved, reference issue #175, #191.  Please visit the [MigAz Releases](https://github.com/Azure/migAz/releases) and ensure you download at least v2.4.4.0, in which this issue should be resolved.

Please advise further if you are still seeing the issue; however, it should be resolved as of that release.

**Comment by recintoit** [comment]
Thank you, the new release has this resolved.
