### ISSUE TITLE
can not migration load balance public ip

### ISSUE THREAD

**Issue by imzhu** [Azure/migAz#210]
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at MigAz.Azure.UserControls.LoadBalancerProperties.<cmbLoadBalancerType_SelectedIndexChanged>d__8.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\UserControls\LoadBalancerProperties.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by imzhu** [comment]
migration ARM VM，migaz 2.4.4

**Comment by ruandersMSFT** [comment]
What is the source (i.e. ASM Cloud Service, existing ARM Load Balancer)?

**Comment by chenxin21cn** [comment]
I just tested with v2.4.4.1. This problem has been resolved , but  I found the migrated load balancer resource has the following bugs: 
1) backend pool not associated with correct availibility set
2)missing NAT rule configuration

**Comment by ruandersMSFT** [comment]
Confirming that MigAz doesn't yet have full awareness of the target output for backend pool, LBRs, NAT.  Including need to build out some form of "property editors" here.  Will try to complete ASAP.
