### ISSUE TITLE
Error after authenticate on Azure

### ISSUE THREAD

**Issue by heinsk** [Azure/migAz#222]
{"odata.error":{"code":"Authentication_Unauthorized","message":{"lang":"en","value":"User was not found."}}}

The remote server returned an error: (403) Forbidden.

   at MigAz.Azure.AzureRetriever.<GetAzureRestResponse>d__19.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureRetriever.cs:line 208
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureTenant.<GetAzureARMDomains>d__23.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureTenant.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureTenant.<InitializeChildren>d__22.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureTenant.cs:line 85
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureContext.<GetAzureARMTenants>d__74.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureContext.cs:line 233
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.UserControls.AzureArmLoginControl.<btnAuthenticate_Click>d__5.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\UserControls\AzureArmLoginControl.cs:line 151
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by ruandersMSFT** [comment]
User was not found.  Utilize a valid Azure AD Account.
