### ISSUE TITLE
Unhandled exception when connecting to Azure

### ISSUE THREAD

**Issue by ByronZA** [Azure/migAz#224]
Having this error on my machine when running the MigAz tool and during the sign-in process.

Wondering if this "C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureContext.cs:line 233
" isn't the problem as I do not have a Directory for Ruanders on my machine.....

user_interaction_required: One of two conditions was encountered: 1. The PromptBehavior.Never flag was passed, but the constraint could not be honored, because user interaction was required. 2. An error occurred during a silent web authentication that prevented the http authentication flow from completing in a short enough time frame
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.WebUI.<AcquireAuthorizationAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenInteractiveHandler.<AcquireAuthorizationAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenInteractiveHandler.<PreTokenRequestAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenCommonAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureTokenProvider.<GetToken>d__15.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureTokenProvider.cs:line 88
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureTenant.<GetAzureARMDomains>d__23.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureTenant.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureTenant.<InitializeChildren>d__22.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureTenant.cs:line 85
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureContext.<GetAzureARMTenants>d__74.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureContext.cs:line 233
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.UserControls.AzureArmLoginControl.<btnAuthenticate_Click>d__5.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\UserControls\AzureArmLoginControl.cs:line 151
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by Brucius** [comment]
can you check if there's a sufficient permission on the subscription access? Usually the permission needs to be Owner to authenticate with MigAz

**Comment by ruandersMSFT** [comment]
I concur with checking permissions of the account you are using.  It is not related to the path not existing on your system (those are the paths at time of build / compilations, debug symbol reference).  The line number you are erroring on specifically goes to query the Tenants and then Subscriptions available.  Ensure the account you are using has sufficient privileges to be able to query available Tenants from the Azure AD Graph API and then the Azure Subscriptions from the Azure Resource Mananger API.

**Comment by ByronZA** [comment]
So it is Owner permission on Subscription layer that is required?

**Comment by ByronZA** [comment]
I have assigned ownership on the subscription and resource layers, yet it still fails with the same error :(

**Comment by ruandersMSFT** [comment]
Old issue with many new releases.  Open new issues if still occuring.
