### ISSUE TITLE
Got this error while trying to fetch ASM resources 

### ISSUE THREAD

**Issue by nitjain** [Azure/migAz#229]
Object reference not set to an instance of an object.
   at MigAz.Azure.Arm.VirtualNetworkGateway.get_SkuName() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\Arm\VirtualNetworkGateway.cs:line 36
   at MigAz.Azure.MigrationTarget.VirtualNetworkGateway..ctor(VirtualNetworkGateway virtualNetworkGateway, TargetSettings targetSettings) in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\MigrationTarget\VirtualNetworkGateway.cs:line 63
   at MigAz.Azure.AzureSubscription.<BindArmResources>d__146.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:line 910
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.UserControls.MigrationAzureSourceContext.<_AzureContext_AfterAzureSubscriptionChange>d__88.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\UserControls\MigrationAzureSourceContext.cs:line 248
![50769612-81077280-12aa-11e9-867f-948c0780f1eb](https://user-images.githubusercontent.com/16927960/50854873-82d14480-1343-11e9-9eb9-caef5cc04c1e.jpg)

**Comment by Brucius** [comment]
@nitjain seems like it has to do with Role permissions on source and target Azure subscriptions
