### ISSUE TITLE
Happens when you go to view template

### ISSUE THREAD

**Issue by Snorky2910** [Azure/migAz#23]
No application is associated with the specified file for this operation
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at MigAz.Forms.ExportResultsDialog.btnViewTemplate_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by PauloRamosGit** [comment]
Hi @Snorky2910 , thank you for reporting the issue.
Can you give us more detail on it? What version are you using?

**Comment by rsanderson2350** [comment]
I'll have to review this further, as I have seen it occur on my machine.  I suspect it has something to do with .json / .html file extension program associations.

**Comment by nbharat3597** [comment]
I encountered this issue while using the MigAz v2.2.9.0. The scenario was pretty simple where i selected couple of VMs (didnt select the vnet and storage account as we've already created new vnet and storage in ARM) and tried to export them. On click of View Template I got the aforementioned error.

**Comment by rsanderson2350** [comment]
While this error is failing to launch an application (such as Visual Studio, Notepad, etc.), the export of the PowerShell and JSON files has occurred and they are available within your export directory.  You can navigate to the directory in Windows Explorer.  When doing so, you are likely to get a prompt that you do not have an application registered to launch the .JSON File type.  At this point, pick which application you would like to open JSON files launched into and ensure you do select the option to "allows open this file type with this program".  We will add code to the v2.3.0.0 release to handle this exception within the application.
