### ISSUE TITLE
Object reference not set to an instance of an object error when trying to export migration job

### ISSUE THREAD

**Issue by ByronZA** [Azure/migAz#237]
Release version: 2.4.4.3
Error Export below:

Object reference not set to an instance of an object.
   at MigAz.Azure.Generator.TemplateGenerator.<BuildVirtualNetworkGatewayConnection>d__58.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\Generator\TemplateGenerator.cs:line 792
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.Generator.TemplateGenerator.<GenerateStreams>d__49.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\Generator\TemplateGenerator.cs:line 181
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Forms.MigAzForm.<RefreshOutput>d__51.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz\Forms\MigAzForm.cs:line 399
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Forms.MigAzForm.<btnExport_Click_1Async>d__45.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz

Any assistance with this error is greatly appreciated

**Comment by ruandersMSFT** [comment]
@JohanPupillo closing #238 as duplicate.

**Comment by ruandersMSFT** [comment]
Temporarily disabled export.  Need to rewrite / test export officially in next build to officially resolve.

**Comment by ruandersMSFT** [comment]
#243
