### ISSUE TITLE
Error Loading Subscriptions

### ISSUE THREAD

**Issue by ctraynor-lightstream** [Azure/migAz#239]
AADSTS50074: Strong Authentication is required.
Trace ID: b0e65a29-b0c5-46b7-b899-fd16405d2e00
Correlation ID: a30d1814-1674-4916-87b9-6dd4233ee613
Timestamp: 2019-07-10 18:40:51Z
   at MigAz.Azure.UserControls.AzureArmLoginControl.<btnAuthenticate_Click>d__5.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\UserControls\AzureArmLoginControl.cs:line 188
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by ruandersMSFT** [comment]
Closing as duplicate issue to issue #192.
