### ISSUE TITLE
{"error":{"code":"NoRegisteredProviderFound}

### ISSUE THREAD

**Issue by SAMIT2016** [Azure/migAz#246]
{"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'australiacentral2' and API version '2019-07-01' for type 'locations/vmSizes'. The supported api-versions are '2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview, 2016-08-30, 2017-03-30, 2017-12-01, 2018-04-01, 2018-06-01, 2018-10-01, 2019-03-01, 2019-07-01'. The supported locations are 'eastus, eastus2, westus, centralus, northcentralus, southcentralus, northeurope, westeurope, eastasia, southeastasia, japaneast, japanwest, australiaeast, australiasoutheast, australiacentral, brazilsouth, southindia, centralindia, westindia, canadacentral, canadaeast, westus2, westcentralus, uksouth, ukwest, koreacentral, koreasouth, francecentral, southafricanorth, uaenorth'."}}

 

The remote server returned an error: (400) Bad Request.

 

   at MigAz.Azure.AzureRetriever.<GetAzureRestResponse>d__19.MoveNext() in C:\Users\ruanders.NORTHAMERICA\Source\Repos\migAz\MigAz.Azure\AzureRetriever.cs:line 208
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.Arm.Location.<InitializeARMVMSizes>d__20.MoveNext() in C:\Users\ruanders.NORTHAMERICA\Source\Repos\migAz\MigAz.Azure\Arm\Location.cs:line 106
--- End of stack trace from previous location where exception was thrown ---

**Comment by ruandersMSFT** [comment]
Closing as duplicate / merged to #180.  Issue reproducible, code fix release momentarily.

**Comment by ruandersMSFT** [comment]
v2.4.4.5 Released.
