### ISSUE TITLE
Issue Selecting Target 2.4.4.5

### ISSUE THREAD

**Issue by jaychunlai** [Azure/migAz#248]
Object reference not set to an instance of an object.
   at MigAz.Azure.UserControls.AzureArmLoginControl.<BindContext>d__2.MoveNext() in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\UserControls\AzureArmLoginControl.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.Forms.AzureNewOrExistingLoginContextDialog.<InitializeDialog>d__5.MoveNext() in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\Forms\AzureNewOrExistingLoginContextDialog.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.UserControls.AzureLoginContextViewer.<btnAzureContext_Click>d__35.MoveNext() in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\UserControls\AzureLoginContextViewer.cs:line 183
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by jaychunlai** [comment]
After several clicks and ignoring the message, I've been able to select to correct subscription target.

**Comment by ruandersMSFT** [comment]
Please try v2.5.0.0 release.
