### ISSUE TITLE
Unhandled Exception when trying to change target subscription

### ISSUE THREAD

**Issue by ByronZA** [Azure/migAz#250]
Good Day all,

I am having an issue where i am not able to change the target subscription at all. Tried the several clicks method and still nothing after the application has completely loaded all the source subscription resources.

This happens when I select the "Change" button in the target Azure Subscription

My unhandled exception error is as per below:

Object reference not set to an instance of an object.
   at MigAz.Azure.Forms.AzureNewOrExistingLoginContextDialog.<InitializeDialog>d__5.MoveNext() in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\Forms\AzureNewOrExistingLoginContextDialog.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.UserControls.AzureLoginContextViewer.<btnAzureContext_Click>d__35.MoveNext() in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\UserControls\AzureLoginContextViewer.cs:line 183
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by ByronZA** [comment]
This seems to be related to guest accounts with Owner access to the subscription. If I use a locally created account it works. Any idea why this may be?

**Comment by ByronZA** [comment]
This problem is caused when you have insufficient access into a subscription when making use of a multi-tenant access account.
