### ISSUE TITLE
DiskSizeInGB cannot be greater than 4095 GB.

### ISSUE THREAD

**Issue by Xumukk** [Azure/migAz#252]
Hi,
Please make changes to the limits similiar to https://github.com/Azure/migAz/issues/78.
Thank you.
Error message below.

DiskSizeInGB cannot be greater than 4095 GB.
   at MigAz.Azure.MigrationTarget.Disk.set_DiskSizeInGB(Int32 value) in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\MigrationTarget\Disk.cs:line 127
   at MigAz.Azure.MigrationTarget.Disk..ctor(IArmDisk sourceDisk, VirtualMachine parentVirtualMachine, TargetSettings targetSettings, ILogProvider logProvider) in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\MigrationTarget\Disk.cs:line 68
   at MigAz.Azure.AzureSubscription.<BindArmResources>d__146.MoveNext() in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:line 962
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.UserControls.MigrationAzureSourceContext.<_AzureContext_AfterAzureSubscriptionChange>d__88.MoveNext() in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\UserControls\MigrationAzureSourceContext.cs:line 248

**Comment by ruandersMSFT** [comment]
With consideration that there are disk sizes in Azure available beyond 4095 GB, what is the purpose/rational for limiting disk size to 4095 GB?  What problem are we trying to solve by limiting to this level?

S80 / P80 disks go up to 32,767 Gb and Ultra Disk is even bring online disk ranges up to 65,535.

Consider [Managed Disk Pricing](https://azure.microsoft.com/en-us/pricing/details/managed-disks/) identifying disks that exceed 4,095 GB within Azure.

**Comment by ruandersMSFT** [comment]
Closing issue.  Moving to issue #254 to expand disk size beyond 4095 GB.
