### ISSUE TITLE
Expand Azure Disk Size beyond 4095 GB

### ISSUE THREAD

**Issue by ruandersMSFT** [Azure/migAz#254]
Azure now allows for higher disk sizes beyond 4095 GB.  Running MigAz on a customer environment in which a VM has disk(s) greater than 4095 GB throws the following error on resource loading, preventing MigAz use.

DiskSizeInGB cannot be greater than 4095 GB.
   at MigAz.Azure.MigrationTarget.Disk.set_DiskSizeInGB(Int32 value) in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\MigrationTarget\Disk.cs:line 127
   at MigAz.Azure.MigrationTarget.Disk..ctor(IArmDisk sourceDisk, VirtualMachine parentVirtualMachine, TargetSettings targetSettings, ILogProvider logProvider) in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\MigrationTarget\Disk.cs:line 68
   at MigAz.Azure.AzureSubscription.<BindArmResources>d__146.MoveNext() in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\AzureSubscription.cs:line 962
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.UserControls.MigrationAzureSourceContext.<_AzureContext_AfterAzureSubscriptionChange>d__88.MoveNext() in C:\Users\Russell\Source\Repos\migAz\MigAz.Azure\UserControls\MigrationAzureSourceContext.cs:line 248

**Comment by ruandersMSFT** [comment]
Please try v2.5.0.0 release.
