### ISSUE TITLE
AzureArmLoginControl

### ISSUE THREAD

**Issue by pamelasalvatori** [Azure/migAz#258]
Object reference not set to an instance of an object.
   at MigAz.Azure.UserControls.AzureArmLoginControl.<BindContext>d__2.MoveNext() in C:\Users\ruanders.NORTHAMERICA\Source\Repos\migAz\MigAz.Azure\UserControls\AzureArmLoginControl.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.Forms.AzureNewOrExistingLoginContextDialog.<rbSameUserDifferentSubscription_CheckedChanged>d__8.MoveNext() in C:\Users\ruanders.NORTHAMERICA\Source\Repos\migAz\MigAz.Azure\Forms\AzureNewOrExistingLoginContextDialog.cs:line 187
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by ruandersMSFT** [comment]
Please try v2.5.0.0 release.
