### ISSUE TITLE
.Azure.Forms.AzureNewOrExistingLoginContextDialog

### ISSUE THREAD

**Issue by pamelasalvatori** [Azure/migAz#260]
Object reference not set to an instance of an object.
   at MigAz.Azure.Forms.AzureNewOrExistingLoginContextDialog.<InitializeDialog>d__5.MoveNext() in C:\migAz\MigAz.Azure\Forms\AzureNewOrExistingLoginContextDialog.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.UserControls.AzureLoginContextViewer.<btnAzureContext_Click>d__35.MoveNext() in C:\migAz\MigAz.Azure\UserControls\AzureLoginContextViewer.cs:line 183
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by ruandersMSFT** [comment]
Please download v2.5.0.1 release and advise if resolved or it encountering another error.  Unable to reproduce this issue locally, unable to recreate the cause/effect.

**Comment by ruandersMSFT** [comment]
#262
