### ISSUE TITLE
when i try to change subscription

### ISSUE THREAD

**Issue by pamelasalvatori** [Azure/migAz#262]
Object reference not set to an instance of an object.
   at MigAz.Azure.UserControls.AzureArmLoginControl.<BindContext>d__2.MoveNext() in C:\migAz\MigAz.Azure\UserControls\AzureArmLoginControl.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.Forms.AzureNewOrExistingLoginContextDialog.<rbSameUserDifferentSubscription_CheckedChanged>d__8.MoveNext() in C:\migAz\MigAz.Azure\Forms\AzureNewOrExistingLoginContextDialog.cs:line 191
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by pamelasalvatori** [comment]
![image](https://user-images.githubusercontent.com/55546662/89536140-bb732180-d7f7-11ea-8038-f7867eae9c02.png)

**Comment by ruandersMSFT** [comment]
Hopefully the last fix needed.  Please try v2.5.0.2.  Thanks, as unable to throw / reproduce this exception locally.
