### ISSUE TITLE
Target Azure subscription

### ISSUE THREAD

**Issue by pamelasalvatori** [Azure/migAz#263]
The underlying connection was closed: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)

**Comment by ruandersMSFT** [comment]
Try again?  This is a network / communication level error, and is not addressed via a code change.
