### ISSUE TITLE
Cannot Select Other Subscription

### ISSUE THREAD

**Issue by curtisforsyth** [Azure/migAz#27]
When attempting to perform a migration from ASM to ARM using v2 I cannot select the new CSP subscription I would like to migrate the ASM resources into.

My source has the option of both subscriptions, but the target only has the one that's been selected in the source.

**Comment by curtisforsyth** [comment]
Also, get this error when attempting to change the source subscription.

*****************ERROR MESSAGE***************************

<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>ForbiddenError</Code><Message>The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.</Message></Error>

The remote server returned an error: (403) Forbidden.

   at MigAz.Azure.AzureRetriever.<GetAzureAsmResources>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureRetriever.<GetAzureAsmVirtualNetworks>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.UserControls.Migrators.AsmToArm.<_AzureContextSourceASM_AfterAzureSubscriptionChange>d__18.MoveNext()

**Comment by rsanderson2350** [comment]
@curtisforsyth MigAz ASM To ARM v2.1.0.0 has been submitted as a Pull Request and should be merged within the next 12 hours.  Can you please retry your operations in this new release and if the reported issue is resolved?  If it is not resolved, can you please provide an update on steps to reproduce and any error messages?  Thanks.

**Comment by PauloRamosGit** [comment]
Hi @curtisforsyth , can you confirm if this issue is now solved?

**Comment by curtisforsyth** [comment]
Hey Paulo,  the fixes worked well except the template for the install process "HTML" file still has the source subscription ID in it.

I.E. - I can now select the destination subscription, but when exporting the templates it still has the source sub-ID in the commands.

No big deal to adjust.  Overall, super awesome product and a great time-saver.  Really appreciate the effort put into this.

I did recently have a client with some performance issues with a SQL deployment after the process was completed, but that's another thing we'll be looking into so we can rule out the deployment.

**Comment by rsanderson2350** [comment]
@curtisforsyth We do have the Source Subscription issue identified and resolved (available soon in the next release).  For the VM with slow performance, consider if it was migrated to Premium storage to provider higher iops per disk.

**Comment by PauloRamosGit** [comment]
Hi @curtisforsyth , can you check if this issue is solved with the latest 2.2.1.0?

**Comment by rsanderson2350** [comment]
A newer release is now available.  Please advise of any issues you observe with the updated release.  Thanks.  This issue should be resolved/closed.

**Comment by geeyen88** [comment]
Getting a very similar if not the same error during login.  Note able to select one of two valid directories.  
MigAz version:   2.2.9.0.

Please help.
Thank you.

Getting the following error:


<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>ForbiddenError</Code><Message>The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.</Message></Error>

The remote server returned an error: (403) Forbidden.

   at MigAz.Azure.AzureRetriever.<GetAzureRestResponse>d__84.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.AzureRetriever.<GetAzureAsmResources>d__82.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureRetriever.<GetAzureAsmNetworkSecurityGroups>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Migrators.AsmToArm.<BindAsmResources>d__82.MoveNext()

**Comment by geeyen88** [comment]
thank you. all working for me.    when selecting dynamic ip ... it always selects static ip.  but i can work my way round this by manually modifying the template.   ... using version 2.2.11.0.
