### ISSUE TITLE
ARM Managed Disk VM

### ISSUE THREAD

**Issue by hinyu98** [Azure/migAz#33]
ARM to ARM for VM with Managed Disk seems not supported

Getting Error as Below

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at MIGAZ.Window.AutoSelectDependencies(ItemCheckedEventArgs listViewRow)
   at MIGAZ.Window.lvwVirtualMachines_ItemChecked(Object sender, ItemCheckedEventArgs e)
   at System.Windows.Forms.ListView.OnItemChecked(ItemCheckedEventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by PauloRamosGit** [comment]
Hi @hinyu98 , that is correct. We are working to deliver that still this week.

**Comment by sjkeerthi** [comment]
@PauloRamosGit  , we are receiving the same error as mentioned by the original poster. Is it possible to get a build that fixes this?

**Comment by willstg** [comment]
Hello, in the Microsoft Azure Government Environment, this error is still showing, even though Managed Disks are also available.  Could we get a quick hot fix to enable?

**Comment by rsanderson2350** [comment]
Working to release a new Managed Disk version this weekend, proceeding to close issue requesting Managed Disk support per this upcoming release.
