### ISSUE TITLE
getting below issue with 2.19.9

### ISSUE THREAD

**Issue by adityakumar60** [Azure/migAz#40]
Index was outside the bounds of the array.
   at MigAz.Azure.Arm.Disk.get_StorageAccountBlob()
   at MigAz.Azure.MigrationTarget.Disk..ctor(Disk sourceDisk)
   at MigAz.Azure.MigrationTarget.VirtualMachine..ctor(AzureContext azureContext, VirtualMachine virtualMachine)
   at MigAz.UserControls.Migrators.AsmToArm.<_AzureContextSourceASM_AfterAzureSubscriptionChange>d__19.MoveNext()

**Comment by rsanderson2350** [comment]
2.2.0.0 build compiled https://github.com/rsanderson2350/migAz/blob/master/Release/MigAz%20v2.2.0.0.zip  Awaiting pull request merge.

**Comment by PauloRamosGit** [comment]
Hi @adityakumar60 , can you please check if the problem is solved with the new 2.2.1.0?

**Comment by adityakumar60** [comment]
Hi Paulo,

Sorry to say but new release has lots of issues.

1. It does not give proper availability set names
2. Does not create dependencies as well like load balancers for cloud
service.
3. It give an error virtual network does not found, if we use existing VNet.

Request you to please look into it.

Thanks,
Aditya

**Comment by rsanderson2350** [comment]
A newer release is now available.  Please advise of any issues you observe with the updated release.  Thanks.
