### ISSUE TITLE
Null reference exception when retrieving VM

### ISSUE THREAD

**Issue by Soruk** [Azure/migAz#42]
Hello,

With the latest version 2.2, I get the following exception when the program parses ASM VM machines after choosing a subscription to migrate:

Object reference not set to an instance of an object.
   at MigAz.Azure.Asm.VirtualMachine..ctor(AzureContext azureContext, CloudService asmCloudService, ISettingsProvider settingsProvider, XmlNode virtualMachineXml, Hashtable vmDetails)
   at MigAz.Azure.AzureRetriever.<GetAzureAsmVirtualMachine>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.Asm.CloudService.<LoadChildrenAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureRetriever.<GetAzureAsmCloudServices>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.UserControls.Migrators.AsmToArm.<_AzureContextSourceASM_AfterAzureSubscriptionChange>d__26.MoveNext()

When debugging, it fails on line 69 of VitulaMachine.cs file, because  `_XmlNode.SelectSingleNode("//ConfigurationSets/ConfigurationSet[1]/SubnetNames/SubnetName")` is null.
There should be a test for null as it is made for other properties:
```
 if (_XmlNode.SelectSingleNode("//ConfigurationSets/ConfigurationSet[1]/SubnetNames/SubnetNames") != null)
            {
                primaryNetworkInterfaceIpConfiguration.SubnetName = _XmlNode.SelectSingleNode("//ConfigurationSets/ConfigurationSet[1]/SubnetNames/SubnetName").InnerText;
            }
```
Regards
Aleksander Kasprzyk

**Comment by rsanderson2350** [comment]
Have issued a new pull request for version 2.2.1.0 to be published.  Please let me know if you run into any other issues.  Thanks!

**Comment by rsanderson2350** [comment]
This issue should be resolved in the last two releases.
