### ISSUE TITLE
unhandle exception enent for v2.2.3.0

### ISSUE THREAD

**Issue by katomel4** [Azure/migAz#49]
<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>ForbiddenError</Code><Message>The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.</Message></Error>

The remote server returned an error: (403) Forbidden.

   at MigAz.Azure.AzureRetriever.<GetAzureRestResponse>d__79.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.AzureRetriever.<GetAzureAsmResources>d__77.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureRetriever.<GetAzureAsmNetworkSecurityGroups>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.UserControls.Migrators.AsmToArm.<_AzureContextSourceASM_AfterAzureSubscriptionChange>d__29.MoveNext()

**Comment by rsanderson2350** [comment]
This should be handled via try/catch in the next version.  Version 2.2.4.0 is awaiting PR and will be available as soon the PR is processed.

**Comment by gszeifert** [comment]
The error is still present in version 2.2.5.0.

**Comment by rsanderson2350** [comment]
Should be handled better with v2.2.6.0, per UI separation of ASM vs ARM.

**Comment by gszeifert** [comment]
No more errors. Thanks.

**Comment by PauloRamosGit** [comment]
Solved
