### ISSUE TITLE
Disks larger than 1023GB

### ISSUE THREAD

**Issue by wrapmaster4500** [Azure/migAz#78]
Hi guys, 
Since MS have added up to 4TB disk sizes on ARM, is there any plans to account for this scenario?

DiskSizeInGB cannot be greater than 1023.
   at MigAz.Azure.MigrationTarget.Disk.set_DiskSizeInGB(Int32 value)
   at MigAz.Azure.MigrationTarget.Disk..ctor(IArmDisk sourceDisk)
   at MigAz.Azure.MigrationTarget.VirtualMachine..ctor(AzureContext azureContext, VirtualMachine virtualMachine, List`1 targetVirtualNetworks, List`1 targetStorageAccounts, List`1 networkSecurityGroups)
   at MigAz.Azure.AzureRetriever.<LoadARMVirtualMachines>d__128.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.AzureRetriever.<BindArmResources>d__132.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Migrators.AsmToArm.<BindArmResources>d__63.MoveNext()

**Comment by rsanderson2350** [comment]
@wrapmaster4500 I have expanded this to 4095GB with version 2.2.14.0

**Comment by wrapmaster4500** [comment]
Thanks a lot.
