### ISSUE TITLE
Remote Server returned an erorr: (403) Forbidden.

### ISSUE THREAD

**Issue by ShaXam-King** [Azure/migAz#83]
Hi!

As soon as the sign-on process is complete (in the new migration interface) I get an error.  I copied to clipboard and pasted below.  The account I am using to log in has subscription admin rights but is an MS account and set for multi-step auth...which does succeed.  I see that the process returns "User was not found".  Does this require an account from an AAD tenant?

{"odata.error":{"code":"Authentication_Unauthorized","message":{"lang":"en","value":"User was not found."}}}

The remote server returned an error: (403) Forbidden.

   at MigAz.Azure.AzureRetriever.<GetAzureRestResponse>d__84.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MigAz.Azure.AzureRetriever.<GetAzureARMResources>d__83.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureRetriever.<GetAzureARMDomains>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureTenant.<InitializeChildren>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.AzureRetriever.<GetAzureARMTenants>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.UserControls.AzureArmLoginControl.<btnAuthenticate_Click>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by TR-OCG** [comment]
In MigAZ, login and wait until you have the above error. Click OK

Go to Log tab in the bottom left pane

you will see MigAZ trying to access the various subscriptions listed in your portal, the last entry will be the one failing, identify the tenant and either remove it or confirm permissions, I had the same error, it was my visual studio subscription that was causing the 403 on the graph api. 

You can still select the subscriptions you have access to and then the tenants within these subscriptions
