### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by smithnr** [Azure/migAz#85]
Object reference not set to an instance of an object.
   at MigAz.Azure.AzureRetriever.<GetAzureARMNetworkInterfaces>d__74.MoveNext() in C:\Source\migAz-master\MigAz.Azure\AzureRetriever.cs:line 1079
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MigAz.Azure.AzureRetriever.<GetAzureARMNetworkInterface>d__75.MoveNext() in C:\Source\migAz-master\MigAz.Azure\AzureRetriever.cs:line 1112
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MigAz.Azure.Arm.BackEndAddressPool.<InitializeChildrenAsync>d__4.MoveNext() in C:\Source\migAz-master\MigAz.Azure\Arm\BackEndAddressPool.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MigAz.Azure.Arm.LoadBalancer.<InitializeChildrenAsync>d__5.MoveNext() in C:\Source\migAz-master\MigAz.Azure\Arm\LoadBalancer.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MigAz.Azure.AzureRetriever.<GetAzureARMLoadBalancers>d__81.MoveNext() in C:\Source\migAz-master\MigAz.Azure\AzureRetriever.cs:line 1243
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MigAz.Azure.AzureRetriever.<LoadARMLoadBalancers>d__126.MoveNext() in C:\Source\migAz-master\MigAz.Azure\AzureRetriever.cs:line 1793
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MigAz.Azure.AzureRetriever.<BindArmResources>d__132.MoveNext() in C:\Source\migAz-master\MigAz.Azure\AzureRetriever.cs:line 1985
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MigAz.Migrators.AsmToArm.<BindArmResources>d__63.MoveNext() in C:\Source\migAz-master\MigAz\Migrators\AsmToArm.cs:line 1033

**Comment by rsanderson2350** [comment]
Have you been able to verify if this is still occurring for you using v2.3.0.1?

**Comment by rsanderson2350** [comment]
Current version now up to 2.3.3.3, closing issue, no further reproduction of error reported to date.
