### ISSUE TITLE
An unhandled exception has occured n MigAz

### ISSUE THREAD

**Issue by ihsan18886** [Azure/migAz#95]
Object reference not set to an instance of an object.
   at MigAz.Forms.UnhandledExceptionDialog..ctor(ILogProvider fileLogProvider, Exception e)
   at MigAz.Migrators.AsmToArm.<BindAsmResources>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Migrators.AsmToArm.<_AzureContextSourceASM_AfterAzureSubscriptionChange>d__24.MoveNext()

**Comment by rsanderson2350** [comment]
Are you able to verify if this has been resolved using the latest version (v2.3.1.0)?

**Comment by pgeorgesamuel** [comment]
Same issue with the new release. 
Object reference not set to an instance of an object.
   at MigAz.Azure.UserControls.TargetTreeView.<AddMigrationTargetToTargetTree>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Migrators.AsmToArm.<treeASM_AfterCheck>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by rsanderson2350** [comment]
v2.4.0.0 has been released.  Please advise if this is still occurring.  If it is, please run using the Debug version to try to provide a source code line #.
