### ISSUE TITLE
MigAz Unhandled Exception

### ISSUE THREAD

**Issue by AndreaFranceschini** [Azure/migAz#98]
No application is associated with the specified file for this operation
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at MigAz.Forms.ExportResultsDialog.btnViewTemplate_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Jide-Jimoh** [comment]
I second this issue. It's giving me a hard time trying to move resources from PAYG to CSP. Using ARM to ARM

**Comment by rsanderson2350** [comment]
Closing as a duplicate issue report to #23 .  While this error is failing to launch an application (such as Visual Studio, Notepad, etc.), the export of the PowerShell and JSON files has occurred and they are available within your export directory.  You can navigate to the directory in Windows Explorer.  When doing so, you are likely to get a prompt that you do not have an application registered to launch the .JSON File type.  At this point, pick which application you would like to open JSON files launched into and ensure you do select the option to "allows open this file type with this program".  We will add code to the v2.3.0.0 release to handle this exception within the application.
